class AlreadyExists(Exception): ...


class AlreadyAnswered(Exception): ...


class DoesNotExist(Exception): ...


class UnAuthenticated(Exception): ...


class UnexpectedNodeResponse(Exception): ...
